### ISSUE TITLE
Add-on description has no link to online version

### ISSUE THREAD

**Issue by dirkfeytons** [palant/easypasswords#15]
I've just installed the add-on (version 1.0.1) in my Firefox 45.0.2 on Windows 7. When going to the options screen the text mentions there's an online version available but that text is not a link (as it is on https://palant.de/2016/04/19/easy-passwords) so it's a bit hard to find that online version :)

**Comment by palant** [comment]
Well, Add-ons Manager shows the description from https://addons.mozilla.org/addon/easy-passwords/ but with pretty much all markup removed, adding a link isn't really possible. I changed the description now so that the link will be displayed as text in Add-ons Manager, that's the best I can do.

**Comment by dirkfeytons** [comment]
OK for me; thanks.
