### ISSUE TITLE
Fill in focused field only

### ISSUE THREAD

**Issue by Noitidart** [palant/easypasswords#16]
I focused the text field, then clicked fill in. I expected it to fill just the currently focused field. But it filled out all 3 fields. I was changing my password, so it overwrote the old password field.

![](http://i.imgur.com/GsLXf6X.png)

https://www.textnow.com/account#/changepassword

**Comment by palant** [comment]
Filling in focused field only appears to be a common expectation. I guess Easy Passwords should look at the focused field first and only fall back to filling out everything if the focused field isn't a password field.

**Comment by Noitidart** [comment]
Thanks!
I was just curious, what scenarios did you encounter where more then one field needed to be auto filled? The only other that I can imagine is having to fill out two fields for "Password" and "Confirm Password" during password changes/registration.

**Comment by palant** [comment]
The typical scenario are pages with more than one form, e.g. pages featuring both a registration and a login form. Before trying to guess which one you are using, it's easier to fill out all.

**Comment by Noitidart** [comment]
Oh! That makes sense. Cool I'm loving this thanks!
