### ISSUE TITLE
Provide a JS version hosted somewhere

### ISSUE THREAD

**Issue by fmarier** [palant/easypasswords#18]
First of all, thanks so much for creating a password generator with a focus on security :) It's about time that someone writes a usable and modernized version of pwdhash.

One of the things that made pwdhash so useful IMO is the fact that you could use it everywhere. That means having a Chrome extension for it, but also, and perhaps more importantly, having a JS version of it on <https://www.pwdhash.com> that runs the same algorithm in client-side JS.

Obviously, it's much weaker to use that site from a security point of view, but it's the ultimate convenience for when you need to access your password using someone else's browser. It would also enable occasional use in browsers that don't have an EasyPasswords extension.

**Comment by palant** [comment]
There is one already: https://palant.de/easypasswords-online.html (linked from extension description). I definitely don't recommend using it regularly however.

**Comment by palant** [comment]
Note that it will only work with Firefox, Chrome or Edge (latter not tested), others don't support WebCrypto API.

**Comment by fmarier** [comment]
> There is one already: https://palant.de/easypasswords-online.html (linked from extension description). I definitely don't recommend using it regularly however.

Ah, I completely missed that, sorry!

I submitted #20 in order to add it to the place where I was looking when I checked out your extension.
