### ISSUE TITLE
Lastpass password vault import

### ISSUE THREAD

**Issue by kzar** [palant/easypasswords#26]
I'm (hopefully!) going to migrate over from LastPass, but since I have been using LastPass for some time I have a lot of passwords and notes to migrate.

[LastPass provides a way to export data to a CSV file](https://lastpass.com/support.php?cmd=showfaq&id=1206) and it would be great if I could import that straight into Easy Passwords.

**Comment by palant** [comment]
For reference, I tried exporting passwords and the columns are:

     url,username,password,extra,name,grouping,fav

In order to associate the passwords properly, the straightforward approach would be extracting the host name from the URL field and then marking it an an alias for "grouping" unless they are identical.

**Comment by kzar** [comment]
Another problem is that LastPass supports "secure notes" which are basically a text blob with a title. I used these extensively and would need to be able to import, search for, view and otherwise manage these too.

(I guess the only part blocking this issue is the ability to store the secure notes, so that they can be imported.)

**Comment by palant** [comment]
Frankly, supporting anything like "secure notes" in Easy Passwords would be out of scope. I could merely imagine converting notes into passwords with some special name. It depends on how these are stored however (in particular, what they look like in this CSV file).

**Comment by kzar** [comment]
Just had a look, the `extra` field contains a double quoted string which contains the notes for an entry (newlines and all). In the case of secure notes, only the extra and name fields are used:

```
http://sn,,,"Note
content
goes
here",Title of note,Secure Notes,0
```

It's a shame if you consider them to be out of scope for Easy Passwords, IMHO they are pretty much an essential feature. Adding notes to entries, and notes without entries is something I use a lot.

**Comment by palant** [comment]
Integrating notes would be fairly complicated from the usability point of view, I'd rather not make the extension too complicated. In addition, this undermines the basic concept of storing as little confidential information as possible - encrypted or not (in particular, encrypted information cannot be part of a paper backup). So it's definitely not on my list any time soon.

**Comment by kzar** [comment]
I don't think anything is blocking this issue any more, we have a place for user names and notes. We decided to put give notes with no associated password with the domain `notes.invalid` and I assume the user name of the note's title.

The main question is how the interface should look, I suppose generally this feature will be something that is only used when the extension is first launched, but we should still probably allow for the user to use it later too. Since the feature will be very rarely used we should not display a button for it too prominently after the initial launch of the extension, but other than that I'm not sure how it should look.

- Should we display a button on the panel and / or in the all passwords page? (Perhaps there should be a special "General tools" button in the panel?)
- How can we make it easy for new users to find this feature?
- How can we avoid it wasting space in the interface after the user has finished using it and will likely never need it again?

Another thing I considered is how can we make it clear to the user what will be imported? I guess it would be nice to have a page that listed everything that was due to be imported allowing the user to proceed / cancel, but that would be quite a lot of work. I guess we have to decide how important that is.

**Comment by kzar** [comment]
Oh cool I didn't realise there was already an import feature. In that case this is much easier than I feared :)

**Comment by curiosity-seeker** [comment]
I exported my passwords in Lastpass to a csv file and tried to import it in Easy Passwords 1.1.4 (which is the latest version on AMO). Unfortunately I only get an "Unknown data format" error message. It seems that only the JSON format is supported. Is this the expected behaviour? If it is that would be unfortunate as this would make switching from Lastpass rather difficult.

**Comment by kzar** [comment]
So far it's unsupported since I've not found the time to work on this yet :( sorry

**Comment by curiosity-seeker** [comment]
I see - thanks for your answer! I've noticed that there are tools for converting csv to json. I'll try that for now.

**Comment by palant** [comment]
They aren't likely to convert CSV to the *right* kind of JSON - currently Easy Passwords will only accept data that Easy Passwords itself created, nothing else.

**Comment by curiosity-seeker** [comment]
That's a pity. So I will have to wait until I can switch to Easy Password.

**Comment by kzar** [comment]
It's not finished, or even fully working, but I've made a good start https://github.com/palant/easypasswords/compare/master...kzar:26-lastpass-import. @palant Would you mind having a look at what I've got so far? I'd be interested to know if you think the approach is OK, also there are a number of FIXME comments, some of which are open questions.

**Comment by kzar** [comment]
I've got the Lastpass importer more or less working now, my passwords and notes are in my Easy Passwords vault. Tests are passing as well. More work to do though, I need to write more tests and there are still quite a few open questions.

**Comment by palant** [comment]
This has been implemented now.
