### ISSUE TITLE
Add a way to securely store notes for passwords

### ISSUE THREAD

**Issue by kzar** [palant/easypasswords#33]
During the discussion for issue #22 we decided to add the ability to store notes and additional form field values for passwords. Initially we will just add the ability to store notes and that's what this issue is about.

Here's @palant's design from that discussion, tweaked to remove anything unrelated / out-dated:

- We have additional metadata on the passwords, it is optional however. Additional metadata is encrypted in the data storage.
- There should be one more icon next to the password saying "Notes" in the tooltip. It's probably best to place it on the right side of the password name in the listing so it's clearly different from the password retrieval icons but one still wouldn't click on the delete icon by mistake.
- By default, this icon should be partially transparent. It should only be black if any data exists there.
- The view should show the site and password name as text. There should be a label "Notes:" followed by a multi-line text area - for arbitrary text notes. There should be two buttons: "Save" and "Cancel."
- All passwords page needs to indicate when a password has stored form notes. This data is encrypted so there should be an additional button to show the notes, similar to actual passwords.

**Comment by palant** [comment]
Now that the "all actions" menu has been [added](https://github.com/palant/easypasswords/commit/0a63563287040459ef8df02f4d582f6bc1204bd1), this is where "notes" belongs into. Whether notes exist already shouldn't be indicated by icon transparency then - the label should rather say "Add notes" or "Edit notes" depending on our scenario. Also, password name tooltip needs to indicate that notes exist now in the passwords list as well.

**Comment by kzar** [comment]
Cool OK, will update this when I get a chance.
