### ISSUE TITLE
"Generate new password for this user name" button shouldn't be listed for legacy passwords

### ISSUE THREAD

**Issue by kzar** [palant/easypasswords#39]
So that a new password can be generated for a record without changing its user name or other details we have a revision field. The "Generate new password for this user name" button allows the revision to be conveniently adjusted for a record.

Since the revision field serves no purpose for legacy passwords it seems wrong to display the  "Generate new password for this user name" button for them.

**Comment by palant** [comment]
No, having this button for legacy passwords is intentional - e.g. you might want to replace a legacy password with a generated one, this button will generate a password with default parameters and revision number 2. So unless this doesn't work correctly this issue is invalid.

**Comment by kzar** [comment]
Ah right, sorry I assumed it would bump the revision of the existing password.
