### ISSUE TITLE
Fails to paste passwords

### ISSUE THREAD

**Issue by CharlesNovotny** [palant/easypasswords#40]
I don’t know whether EasyPasswords updates itself automatically or not but pasting passwords has recently stopped working, possibly after an auto-update. **(Screenshot below.)** Restarting the browser (Chrome) doesn’t help. EasyPasswords still allows copying passwords to clipboard.

Error message: “The operation failed unexpectedly. The message port closed before a response was received.”

I don’t know how this is related but another change in behaviour appeared at the same time: EasyPasswords used to auto-lock itself but now it doesn’t. I had to set auto-locking in options manually to bring back the original behaviour. Such changes are slightly disconcerting and make me wonder whether someone was tinkering with my browser.

P.S. It’s an ingenious extension and I love Mr. Palant for creating it. It’s perfect in every way and, I guess, superior to every other password keeping solution. I created this GitHub account only to report this bug. Before EasyPasswords, creating throwaway accounts was an untenable task, and requirements to register discouraged me from using many websites.

![2016-09-25 the operation failed unexpectedly censored](https://cloud.githubusercontent.com/assets/22433061/19019226/cebdfcb6-8877-11e6-8647-f8b066f24691.png)

**Comment by palant** [comment]
Confirmed, it's a regression from https://github.com/palant/easypasswords/commit/20189e608e3df00114ad7407dc66819f8574c021 (I could have sworn that I tested this functionality but apparently I didn't). The important change seems to be that the code notices the exception now - before this commit it happily ignored the error and everything was working fine as the response is irrelevant.

**Comment by palant** [comment]
Easy Passwords 1.1.5 has been released, you should get the update shortly. Thank you for taking the time and creating this bug report.

**Comment by CharlesNovotny** [comment]
It works now. Thank you!

> Thank you for taking the time and creating this bug report.

My little contribution to this project ☺.
