### ISSUE TITLE
Feature request - hotkey

### ISSUE THREAD

**Issue by Noitidart** [palant/easypasswords#43]
May you please add a hotkey. It's easy to just hit hotkey and type master password. It would be awesome with this feature - https://github.com/palant/easypasswords/issues/42 - so as soon as I type that master password then it auto fills.

**Comment by Noitidart** [comment]
Thank you sir! I can't believe this addon does not have more users. It is the most trustworthy pw manager! Your site really helps me out when I'm on the go too! :)

**Comment by Noitidart** [comment]
In Firefox on Windows Ctrl + Shift + E has been opening the "network" pane in dev tools. :( Is this firefox-native hotkey breaking the hotkey in here? Its not work for me anymore :(

**Comment by Noitidart** [comment]
Aw drats. Thanks for the quick reply!

**Comment by Noitidart** [comment]
On my mac this thing is soooo great I do Command + Shift + E and all mouse-less. But on my Windows its real tough. May we please consider supplementing/add a 2nd keyboard shortcut, of maybe Alt + Shift +E? :)

**Comment by palant** [comment]
This is merely the default shortcut key, it cannot possibly work everywhere (wrote about it [10 years ago](https://adblockplus.org/blog/shortcut-keys-are-hard), it's still the same). The browser is supposed to provide a way to change this shortcut key. It seems that Mozilla is [finally making progress on this](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384).

**Comment by Noitidart** [comment]
Oh nice thanks for that link! I'll wait on them and comment there.

**Comment by Noitidart** [comment]
Just wanted to share thanks for sharing the link

> 
> 
> This is merely the default shortcut key, it cannot possibly work everywhere (wrote about it [10 years ago](https://adblockplus.org/blog/shortcut-keys-are-hard), it's still the same). The browser is supposed to provide a way to change this shortcut key. It seems that Mozilla is [finally making progress on this](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384).

Just wanted to share thanks for sharing this link! I Just checked today and I can modify shortcuts now!! https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Updating_shortcuts

**Comment by palant** [comment]
Oh, finally! I think I'll change the default for Firefox anyway, but this is really good news nevertheless.
