### ISSUE TITLE
Choosing our own salt

### ISSUE THREAD

**Issue by Ryakna** [palant/easypasswords#44]
Hi,

From what I've read, I understand that the extension uses the username as the salt. Would it be possible to add an option to write our own salt for that website?
Currently, I can add my own salt by writing it instead of the username, but by doing that, I cannot then use the option to auto-fill the username on that website and I'd like to, as it's a lot faster.

Thanks

**Comment by palant** [comment]
You can use the revision field for that, it becomes part of the salt - the primary use is generating different passwords for the same username when a website demands password rotating. While the revision is usually numeric, it can actually be an arbitrary text.
