### ISSUE TITLE
Disable storage

### ISSUE THREAD

**Issue by lkraider** [palant/easypasswords#45]
I am trying out the extension and noticed it stores the list of passwords generated. I would prefer to disable that and rely on regenerating the passwords everytime, so there is no central list of websites I visit/usernames available. Is this possible?

**Comment by palant** [comment]
No, without this functionality the extension serves no purpose. The very point is that you don't need to remember the password generation parameters for every website. If you don't need that, you can use the [online version](https://palant.github.io/easypasswords/online.html) (it's recommended that you download this page and use the local version).

**Comment by lkraider** [comment]
Thanks for the info. I prefer not to store anything on the computer and use default parameters, so I may fork the extension to do just that. I really like it 👍

**Comment by palant** [comment]
Without storing data, the extension is merely a more awkward variant of the online version - requiring multiple steps where one would suffice. The only advantage is that it determines the current site automatically, but even this gets complicated when multiple sites share passwords.

Note that default parameters don't work on every site, quite a few sites have issues with special characters in passwords.

**Comment by lkraider** [comment]
I know, I've been using my own greasemonkey tool for years now (with its own webapp mobile website). Just the fact that the extension is available from the browser for the current page easily is an advantage over the online-only version. I intend on using the online version too, I'll probably make it webapp enabled (meaning iOS can save the page as an app on the homescreen and work offline).

**Comment by palant** [comment]
For reference, #47 is suggesting to encrypt the metadata.

**Comment by lkraider** [comment]
I don't care about encrypting local data, I'll keep using my fork then.
