### ISSUE TITLE
The import / export password button icons aren't obvious enough

### ISSUE THREAD

**Issue by kzar** [palant/easypasswords#49]
Perhaps this is a subjective thing, but to me the password import and export buttons on the all passwords page are the wrong way around. I consider the box to be my Easy Password vault, therefore the icon with the arrow going into the box should be import and an arrow going out of the box should be export.

**Comment by palant** [comment]
They are fairly canonical icons for download/upload, so the other way round it will still be subjective while making less sense. Unfortunately, ionicons icon set doesn't provide more obvious icons for our case and finding other icons that both match ionicons style and are free is non-trivial to say the least.

**Comment by palant** [comment]
The new icons should hopefully make this more obvious. The direction of arrows is reversed, now the box represents your passwords "vault."
