### ISSUE TITLE
The export button doesn't work

### ISSUE THREAD

**Issue by kzar** [palant/easypasswords#50]
When I click the export button on the all passwords page nothing happens. Well that's no true, it seems to populate the exportData element with a data URI, but nothing happens as far as the user's concerned.

I'm using Chrome 57 and building the devbuild from https://github.com/palant/easypasswords/commit/dc4191d0186b1b25ba69a2e10568317e81e79c6e.

**Comment by palant** [comment]
Same Chrome version, same revision - clicking that button results in a file download for me. With the default Chrome settings that file is being written to Downloads folder automatically and you merely see a downloads bar at the bottom. Could it be that your downloads settings are different?

**Comment by kzar** [comment]
I can no longer reproduce the problem, perhaps I had somehow got the extension into a broken state while working on the LastPass importer. Sorry to waste your time.
