### ISSUE TITLE
On mac, cannot use tab to select "wand" 

### ISSUE THREAD

**Issue by Noitidart** [palant/easypasswords#51]
I recently was forced to use mac for some months. In windows, I used to be able to fill in a password with just the keyboard. However in mac, once the easy passwords panel opens, i cannot use tab to select the "Wand". Here is screencast - https://youtu.be/gy11X-BLLto

**Comment by palant** [comment]
Let me guess - https://stackoverflow.com/a/2360/785541?

**Comment by Noitidart** [comment]
Oh my gosh! Macs are so silly! The sensible default would be to match othe OSes and do all controls (at least in my family). Forgive this please, and thanks so much for that system prefs fix. Macs are so silly, it's their way or the highway, I avoided them for 15 years.
