### ISSUE TITLE
Auto fill not detecting itunes.connect field

### ISSUE THREAD

**Issue by Noitidart** [palant/easypasswords#55]
Hi there sir!

For the website - https://itunesconnect.apple.com/ - we use this for submitting iOS apps. Clicking auto-fill is giving "not found" error. Here is screenshot -

![](http://i.imgur.com/CjiTu2C.png)

**Comment by palant** [comment]
Please note the "password fields belong to a different site" part of the message - that's exactly what you have here, the password field is part of a frame originating from idmsa.apple.com. Filling in automatically is actually a bad idea in this case, there is no good solution as long as Apple is obfuscating the party which gets the password.

**Comment by Noitidart** [comment]
Oh wow. Apple is so silly. Thanks for pointing this out! :)
