### ISSUE TITLE
Partial Password support

### ISSUE THREAD

**Issue by NellePfannerstill72** [palant/easypasswords#57]
First of all thank you for this best of class extension.

Unfortunately some sites are using nasty feature sometimes called [partial password](https://en.wikipedia.org/wiki/Partial_Password) which means that instead of submitting your password you have to write only randomly chosen characters from it.

This (anti)feature combined with password managers like yours is a usability nightmare as you have to manually count position of each chars.

I know that KeePass have [PICKCHARS](http://keepass.info/help/base/placeholders.html#pickchars) feature which provides some solution.

Also there is other [firefox extension ](https://addons.mozilla.org/en-US/firefox/addon/password-character-picker) which tries to ease some burden but needs manual copy-pasting from existing password manager.

Do you think easypasswords can implement something to make those sites usable?

**Comment by palant** [comment]
I've never come across any websites doing something like that, from security point of view it's completely crazy. Can you give me some examples? Given that different websites likely implement this different, more examples is better.

**Comment by NellePfannerstill72** [comment]
Yeah, many people are surprised that such oddities exist. I adjusted proper name of this feature and linked to wiki. Here's some [explanation](http://www.amfastech.com/2013/03/what-are-partial-passwords-in-web.html) .

Here's some links. Sorry for foreign language but you can change it to english). Please write some bogus username and it will ask you for selected password chars.

https://login.ingbank.pl/mojeing/app/#login (switch to English at bottom)

https://aliorbank.pl/hades/do/Login (switch to English at upper left)

https://www.pekao24.pl/ClientLogonUK.html (english)

**Comment by palant** [comment]
These seems to be fairly similar. I guess we could recognize multiple password fields on a page, all with `maxlength="1"`. The only issue is figuring out in a generic way what characters we are being asked for. For the scenarios here the number the `name` attribute ends with will do. But these don't seem to be really independent implementation, rather the same contractor working on all of them.

**Comment by NellePfannerstill72** [comment]
I've found webscrypt author [announcement](https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https%3A%2F%2Fwww.v2ex.com%2Ft%2F343887&sandbox=1) with some explanations. Unfortunately he wasn't active recently. I hope we will hear something from him.

**Comment by NellePfannerstill72** [comment]
The are more sites from different countries. It's especially popular in banking :smile:
However many sites require valid login. Some banks that use this technique are mentioned in http://groups.inf.ed.ac.uk/security/passwords/pps.pdf

You can try those (just fill bogus data for username/birth):

https://www.365online.com/online365/spring/authentication?execution=e1s1
https://www.standardlife.co.uk/c1/login.page

**Comment by palant** [comment]
Actually, extracting the position from the `name` attribute has its issues - the first two sites use one-based indexing, the last one zero-based. This can be solved by looking at what other fields are present, but ING only has the fields in the document which are actually meant to be filled in.

**Comment by palant** [comment]
Thank you for these additional examples. These also have one-based numbering, so this seems to be prevalent. I guess I'll be assuming one-based numbering unless an input element numbered zero is found.

**Comment by palant** [comment]
The code I added can handle all the examples correctly except for standardlife.co.uk - there the input fields don't offer any clues for the position of the characters in the password. Seems to be as good as it goes.
