### ISSUE TITLE
Can't copy passwords to clipboard anymore

### ISSUE THREAD

**Issue by mrjohnson22** [palant/easypasswords#59]
Clicking any of the "Copy to clipboard" buttons doesn't actually send anything to the clipboard. This started happening ever since the latest update (the one that converted EP to a WebExtension).

**Comment by palant** [comment]
Did you happen to switch off `dom.event.clipboardevents.enabled` preference via `about:config`?

**Comment by palant** [comment]
In case it is that preference, with https://github.com/palant/easypasswords/commit/8b809934dac6066c65d407dafaa7e3b4aff92d34 it should no longer affect Easy Passwords. I plan to have a new release soon.

**Comment by mrjohnson22** [comment]
Yup, that was it. That's probably not really a bug at all, then. Thanks for finding a workaround, though!

**Comment by palant** [comment]
Great, this is fixed then.

**Comment by palant** [comment]
And Easy Passwords 1.2.1 is out. It will take Mozilla some time to review and approve the update, hopefully not more than a few days however - the changes are minimal.
